# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4938a81829ce819a21af0dd91f33e7861b36c6ba7970605f6107dab23b4e736bd1d64a32c621f250c49a2e55f0802a837e123cfa6de844747a83d19e37e908a8

test:
  secret_key_base: 1cea36978c27758ddbc76a082a786887e6c4d5954be930ca7a7be0469a4d125ba062fd7fd54de410bf06e144bebc455786fb12b3ee148b760df6f2d8bcf0a3fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
